### ISSUE TITLE
url/shorten not triggered

### ISSUE THREAD

**Issue by danito** [mapkyca/KnownBitlyShorten#1]
Hi,
I couldn't make it work on my known installation. I added a 
`error_log($access_token);`
after 

``` php
   \Idno\Core\site()->addEventHook('url/shorten', function(\Idno\Core\Event $event) {
        // Try user binding first
        if ($this->hasBitly()) {
            $access_token = \Idno\Core\site()->session()->currentUser()->bitly['access_token'];
            // Generic access token shorten
        } else if (isset(\Idno\Core\site()->config->config['bitly'])) {
            // Shorten with GAT
            $access_token = \Idno\Core\site()->config->config['bitly']['generic_access_token'];
        }
        if ($access_token) {
            $url = $event->response();
```

but nothing shows up in the logs. I even put a var_dump($event) but still nothing happens.
If I do the same with in addEventHook('url/expandintext',...); it works well.
The strange thing is that when dumping the $event later I can see an entry url/shortener, but without any data.
Any ideas why the url/shortener is not triggered?
Thanks

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownBitlyShorten/issues/1" class="u-in-reply-to"></a>Currently, Known only triggers the shorten API from the share page.

This is done because sharing is an explicit action, whereas in other usages you may not want to shorten a url.

**Comment by danito** [comment]
Thanks, didn't know about the /share page. 
It triggers fine now.
(I addapted my Yourls plugin but it triggers to soon now, it shortens a "0" long url as the response is null as we don't have yet any long url to shorten before sending)

**Comment by danito** [comment]
It's the same for Bitly, when activating your plugin and go to .../share/ I get immediately a warning that "There was a problem shortening that link..."
The trigger for url/shorten is hitting too early.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownBitlyShorten/issues/1#issuecomment-112559555" class="u-in-reply-to"></a>Are you passing the URL? The share page is designed to be called from the bookmarklet or firefox/chrome plugin...

**Comment by danito** [comment]
:facepalm: ;-)

**Comment by danito** [comment]
seems that using a url shortener for your posts url is not possible without touching core...

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownBitlyShorten/issues/1#issuecomment-112587016" class="u-in-reply-to"></a>You mean the link that gets syndicated when you push to other services (twitter etc)?

**Comment by danito** [comment]
Yes, the /s/...
One can change the set/getShorturl() functions in core. I dont think
there's a hook before publish.
